---
- name: Install curl
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Install chezmoi
  ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/.local/bin
  args:
    creates: "~/.local/bin/chezmoi"

- name: Copy zshrc
  ansible.builtin.copy:
    src: dotfiles/dot_zshrc
    dest: ~/.zshrc
    mode: 0644