---
- name: Install curl
  become: true
  ansible.builtin.package:
    name: curl
    state: present

- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

# Note: Neovim installed via apt in Ubuntu is too old for lazy.vim
# (lazy.nvim requires Neovim >= 0.8.0)
- name: Install Neovim and other packages 
  become: true
  ansible.builtin.package:
    name:
    - neovim
    - fzf
    - git # required by lazy
    - gcc # required by neovim-treesitter
    - make # required by neovim-treesitter
    state: present

- name: Install chezmoi
  ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/.local/bin
  args:
    creates: "~/.local/bin/chezmoi"

- name: Initialize chezmoi
  ansible.builtin.command: '~/.local/bin/chezmoi init --no-tty --promptChoice "Which Window Manager=kde" --apply --verbose {{ chezmoi_init_url }}'
  args:
    creates: "~/.local/share/chezmoi"